/** Export the leadership memo: run summary + per-branch evidence, as .md. */

import type { RunBundle } from "./types";
import { companyLabel, datasetLabel, fm, pct, share } from "./format";

export function buildMemo(bundle: RunBundle): string {
  const { run } = bundle;
  const lines = [
    `# ${run.metric} — ${run.period_a} → ${run.period_b}`,
    ``,
    `${companyLabel(run.company)} · ${datasetLabel(run.dataset)} · explained ${Math.round(run.explained_share * 100)}% · generated by Delta Ledger`,
    ``,
    run.summary_md,
    ``,
    `---`,
    ``,
    `## Evidence appendix`,
  ];
  for (const b of bundle.branches) {
    if (b.depth > 0 || b.state === "capped") continue;
    lines.push(``, `### ${b.name}`);
    lines.push(`- ${fm(b.value_a)} → ${fm(b.value_b)} (${pct(b.delta_pct)}), ${share(b.share)} of the move, z ${b.zscore ?? "—"}`);
    for (const claim of b.evidence?.claims ?? []) {
      lines.push(`- ${claim.text} \`[${claim.tag}]\``);
    }
  }
  const capped = bundle.branches.filter((b) => b.depth === 0 && b.state === "capped");
  if (capped.length) {
    lines.push(``, `### Below the materiality floor`);
    for (const b of capped) lines.push(`- ${b.name}: ${fm(b.delta_abs)} (${share(b.share)})`);
  }
  lines.push(``, `_All figures computed by the deterministic engine; narrative tags: reported_fact / calculated_attribution / management_commentary / agent_inference._`);
  return lines.join("\n");
}

export function downloadMemo(bundle: RunBundle) {
  const md = buildMemo(bundle);
  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${bundle.run.metric.toLowerCase().replace(/\s+/g, "-")}-${bundle.run.period_b}-memo.md`;
  a.click();
  URL.revokeObjectURL(url);
}
